<a href="https://colab.research.google.com/github/hcantekin/hcantekin.github.io/blob/main/Metatest00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd 
import numpy as np 
import json

In [4]:
df = pd.read_csv('MetaReport_test00.csv')

In [5]:
df.dropna()

,ID,page_name,ad_creation_time,demographic_distribution,delivery_by_region
0,1,The Labour Party,2021-12-16,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""Northern Ireland"",""percentage"":0.00..."
1,2,The Labour Party,2021-12-16,"{""age"":""25-34"",""gender"":""unknown"",""percentage""...","{""region"":""England"",""percentage"":0.913},{""regi..."
2,3,The Labour Party,2021-12-16,"{""age"":""25-34"",""gender"":""unknown"",""percentage""...","{""region"":""England"",""percentage"":0.912082},{""r..."
3,4,The Labour Party,2021-12-16,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""Northern Ireland"",""percentage"":0.00..."
5,6,The Labour Party,2021-12-14,"{""age"":""65+"",""gender"":""male"",""percentage"":0.05...","{""region"":""England"",""percentage"":1}"
...,...,...,...,...,...
5814,5815,The Labour Party,2021-01-11,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""England"",""percentage"":1}"
5815,5816,The Labour Party,2021-01-11,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""England"",""percentage"":1}"
5816,5817,The Labour Party,2021-01-11,"{""age"":""35-44"",""gender"":""unknown"",""percentage""...","{""region"":""England"",""percentage"":1}"
5817,5818,The Labour Party,2021-01-11,"{""age"":""35-44"",""gender"":""female"",""percentage"":...","{""region"":""England"",""percentage"":1}"
5818,5819,The Labour Party,2021-01-11,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""England"",""percentage"":1}"