<a href="https://colab.research.google.com/github/hcantekin/hcantekin.github.io/blob/main/Uk_arts_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('creative_industry_data.csv')
df.head()

,region,industry,1998,1999,2000,2001,2002,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,United Kingdom,"Arts, entertainment and recreation","9,953","10,645","11,339","12,150","13,810","15,830","17,124","18,490",...,"21,912","23,713","24,500","25,075","25,036","27,268","28,147","29,876","22,789","27,432"
1,United Kingdom,"Creative, arts and entertainment activities","2,876","3,098","3,596","3,452","3,955","3,711","3,801","4,334",...,"5,885","6,365","6,135","6,614","6,653","7,312","7,755","8,470","6,251","8,180"
2,England,"Arts, entertainment and recreation","8,747","9,352","9,985","10,714","12,178","13,947","14,926","16,272",...,"18,826","20,438","21,361","22,047","22,175","24,237","25,082","26,668","20,269","24,416"
3,England,"Creative, arts and entertainment activities","2,674","2,894","3,348","3,229","3,736","3,503","3,576","4,114",...,"5,424","5,916","5,775","6,273","6,298","6,936","7,371","8,087","5,996","7,819"
4,North East,"Arts, entertainment and recreation",264,288,296,322,385,450,570,608,...,675,748,757,793,701,717,701,756,509,630

In [8]:
# Convert wide format to long format
df2 = pd.melt(df, id_vars=['region', 'industry'], var_name='date', value_name='value')

df2.head()

           region                                     industry  date  value
0  United Kingdom           Arts, entertainment and recreation  1998  9,953
1  United Kingdom  Creative, arts and entertainment activities  1998  2,876
2         England           Arts, entertainment and recreation  1998  8,747
3         England  Creative, arts and entertainment activities  1998  2,674
4      North East           Arts, entertainment and recreation  1998    264

In [9]:
import json

UK_arts_data = list(df2.T.to_dict().values())

open('UK_arts_data.json','w').write(json.dumps(UK_arts_data))

76656